export default [
  {
    "itemName": "设备地图",
    "status": 'enable',
    "urlPath": "/devicemap",
    "perms": null,
    "type": 0,
    "component": "Layout",
    "pathName": null,
    "meta": null,
    "sortNum": 3,
    "hidden": false,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '设备地图',
    "moduleCode": 'A001',
    "list": [
      {
        "itemName": "设备地图",
        "status": 'enable',
        "urlPath": "/",
        "perms": "deviceMap:list",
        "type": 1,
        "component": "devicemap",
        "pathName": "devicemap",
        "meta": "{\"common\": \"false\",\"hidden\":\"true\"}",
        "sortNum": 1,
        "hidden": false,
        "parentName": "设备地图",
        "moduleName": 'GPS地图',
        "enModuleName": "module_device_place",
        "moduleCode": 'A101',
        "list": [
          {
            "itemName": "设备列表",
            "status": 'enable',
            "urlPath": "",
            "perms": "device:list",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
            "sortNum": 2,
            "hidden": true,
            "parentName": "设备地图",
            "moduleName": '列表模式',
            "moduleCode": 'A201',
            "list": [{
              "itemName": "查询/筛选列表",
              "status": 'enable',
              "urlPath": "",
              "perms": "devicelist:search",
              "type": 2,
              "component": "",
              "pathName": "",
              "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
              "sortNum": 1,
              "hidden": true,
              "parentName": "设备列表",
              "moduleName": '查询/筛选列表',
              "moduleCode": 'A301'
            }]
          },
          {
            "itemName": "统计模式",
            "status": 'enable',
            "urlPath": "",
            "perms": "device:stat",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
            "sortNum": 3,
            "hidden": true,
            "parentName": "设备地图",
            "moduleName": '统计模式',
            "moduleCode": 'A202'
          },
          {
            "itemName": "查询/筛选",
            "status": 'enable',
            "perms": "device:search",
            "type": 2,
            "parentName": "设备地图",
            "moduleName": '查询/筛选',
            "moduleCode": 'A203'
          }
        ]
      },
      {
        "itemName": "设备列表",
        "status": 'enable',
        "urlPath": "devicelist",
        "perms": null,
        "type": 1,
        "component": "common/devicemap/deviceList",
        "pathName": "devicelist",
        "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 2,
        "hidden": true,
        "parentName": "设备地图",
        "moduleName": 'GPS地图',
        "moduleCode": 'A101'
      }
    ],
  },
  {
    "itemName": "全库搜索",
    "status": 'enable',
    "urlPath": "/SuperSearch",
    "perms": null,
    "type": 0,
    "component": "Layout",
    "pathName": null,
    "meta": null,
    "sortNum": 1,
    "hidden": false,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '全库搜索',
    "moduleCode": 'B001',
    "list": [
      {
        "itemName": "全文搜索",
        "urlPath": "superSearch",
        "perms": null,
        "type": 1,
        "component": "common/full-database-search/super-search/index",
        "pathName": "SuperSearch",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-quanwensousuo\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 0,
        "hidden": false,
        "parentName": "全库搜索",
        "moduleName": '综合检索',
        "moduleCode": 'B101',
      },
      {
        "itemName": "全文搜索_详情",
        "urlPath": "superSearchDetail",
        "perms": null,
        "type": 1,
        "component": "common/full-database-search/super-search/detail",
        "pathName": "superSearchDetail",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"全文搜索\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "全库搜索",
        "moduleName": '综合检索',
        "moduleCode": 'B101',
      },
      {
        "itemName": "数据搜索",
        "urlPath": "dataSearch",
        "perms": null,
        "type": 1,
        "component": "common/full-database-search/data-search/index",
        "pathName": "dataSearch",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-shujusousuo\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 1,
        "hidden": false,
        "parentName": "全库搜索",
        "moduleName": '数据搜索',
        "moduleCode": 'B103',
      },
      {
        "itemName": "图片搜索",
        "urlPath": "ImageSearch",
        "perms": null,
        "type": 1,
        "component": "common/full-database-search/image-search/index",
        "pathName": "ImageSearch",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-tupiansousuo\",\"icon-h\":\"icon-1-imagesearch-active.png\",\"belong\":\"\"}",
        "sortNum": 2,
        "hidden": false,
        "parentName": "全库搜索",
        "moduleName": '图片检索',
        "moduleCode": 'B102',
      },
      {
        "itemName": "图片搜索_详情",
        "urlPath": "ImageSearchDetail/:id",
        "perms": null,
        "type": 1,
        "component": "common/full-database-search/image-search/image-detail",
        "pathName": "ImageSearchDetail",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"图片搜索\"}",
        "sortNum": 45,
        "hidden": true,
        "parentName": "全库搜索",
        "moduleName": '图片检索',
        "moduleCode": 'B102',
      }
    ],
  },
  {
    "itemName": "数据中心",
    "status": 'enable',
    "urlPath": "/dataCenterAll",
    "perms": null,
    "type": 0,
    "component": "Layout",
    "pathName": null,
    "meta": "{\"common\": \"true\"}",
    "sortNum": 2,
    "hidden": false,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '数据中心',
    "moduleCode": 'C001',
    "list": [
      {
        "itemName": "全部",
        "status": "enable",
        "urlPath": "dataCenterAll",
        "perms": "dc:wifi:list,dc:wifi:info,dc:wifi:add,dc:wifi:update,dc:wifi:delete",
        "type": 1,
        "component": "common/data-center/all/index",
        "pathName": "dataCenterAll",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-WIFIredian\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 1,
        "hidden": false,
        "parentName": "数据中心",
        "moduleName": '全部',
        "moduleCode": 'C101',
      },
      // {
      //   "itemName": "WIFI热点",
      //   "status": 'enable',
      //   "urlPath": "hotspot",
      //   "perms": "",
      //   "type": 1,
      //   "component": "common/data-center/wifi-hotspot/index",
      //   "pathName": "hotspot",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-WIFIredian\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 2,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": 'WIFI热点',
      //   "enModuleName": "module_probe_wifi",
      //   "moduleCode": 'C102',
      // },
      // {
      //   "itemName": "探针数据",
      //   "status": 'enable',
      //   "urlPath": "probeData",
      //   "perms": "",
      //   "type": 1,
      //   "component": "common/data-center/probe-data/index",
      //   "pathName": "probeData",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-tanzhenshuju\",\"icon-h\":\"icon-2-query-active.png\",\"belong\":\"\"}",
      //   "sortNum": 3,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '探针数据',
      //   "enModuleName": "module_probe_mac",
      //   "moduleCode": 'C103',
      // },
      // {
      //   "itemName": "审计数据",
      //   "status": 'enable',
      //   "urlPath": "auditData",
      //   "perms": "",
      //   "type": 1,
      //   "component": "common/data-center/audit-data/index",
      //   "pathName": "auditData",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-3-query.png\",\"icon-h\":\"icon-3-query-active.png\",\"belong\":\"\"}",
      //   "sortNum": 4,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '审计数据',
      //   "enModuleName": "module_net_web",
      //   "moduleCode": 'C104',
      // },
      // {
      //   "itemName": "电围数据",
      //   "urlPath": "ElectronicFence",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/electronic-fence/index",
      //   "pathName": "ElectronicFence",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-dianweishuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 5,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '电围数据',
      //   "enModuleName": "module_probe_phone",
      //   "moduleCode": 'C105',
      // },
      // {
      //   "itemName": "停车记录",
      //   "status": 'enable',
      //   "urlPath": "carDiscern",
      //   "perms": "",
      //   "type": 1,
      //   "component": "common/data-center/parking-record",
      //   "pathName": "carDiscern",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-tingchejilu\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 6,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '停车记录',
      //   "enModuleName": "module_community_car",
      //   "moduleCode": 'C106',
      // },
      // {
      //   "itemName": "人脸抓拍",
      //   "urlPath": "FaceRecognition",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/face-recognition/index",
      //   "pathName": "FaceRecognition",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-renlianshibieshexiangtou\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 7,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '人脸抓拍',
      //   "enModuleName": "module_community_face",
      //   "moduleCode": 'C107',
      // },
      // {
      //   "itemName": "视频门禁",
      //   "urlPath": "VideoControl",
      //   "perms": "personGate:list,personGate:add,personGate:delete,personGate:update,personGate:info",
      //   "type": 1,
      //   "component": "common/data-center/video-control/index.vue",
      //   "pathName": "VideoControl",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-shipinmenjin\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 8,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '视频门禁',
      //   "enModuleName": "module_community_gate",
      //   "moduleCode": 'C108',
      // },
      // {
      //   "itemName": "视频门禁_人物档案",
      //   "urlPath": "VideoControlDetail/:id",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/all-archives/person-important/person-detail/index.vue",
      //   "pathName": "VideoControlDetail",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"视频门禁\"}",
      //   "sortNum": 30,
      //   "hidden": true,
      //   "parentName": "数据中心",
      //   "moduleName": '视频门禁',
      //   "enModuleName": "module_community_gate",
      //   "moduleCode": 'C108',
      // },
      // {
      //   "itemName": "网吧数据",
      //   "urlPath": "InternetBar",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/Internetbar-data",
      //   "pathName": "InternetBar",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 9,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '网吧数据',
      //   "enModuleName": "module_police_netbar",
      //   "moduleCode": 'C109',
      // },
      // {
      //   "itemName": "防疫数据",
      //   "urlPath": "Antiepidemic",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/antiepidemic-data",
      //   "pathName": "Antiepidemic",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-fangyishuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 10,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '防疫数据',
      //   "enModuleName": "module_police_antiepidemic",
      //   "moduleCode": 'C110',
      // },
      // {
      //   "itemName": "旅业数据",
      //   "urlPath": "Hotel",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/tourism-data",
      //   "pathName": "Hotel",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 11,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '旅业数据',
      //   "enModuleName": "module_police_hotel",
      //   "moduleCode": 'C111',
      // },
      // {
      //   "itemName": "银行业务",
      //   "urlPath": "BankBusiness",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/bank-business",
      //   "pathName": "BankBusiness",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 12,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '银行业务',
      //   "enModuleName": "module_bank_card",
      //   "moduleCode": 'C112',
      // },
      // {
      //   "itemName": "复工复产",
      //   "urlPath": "ResumeWork",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/resume-work",
      //   "pathName": "ResumeWork",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 13,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '复工复产',
      //   "enModuleName": "module_epidemic_resumework",
      //   "moduleCode": 'C113',
      // },
      // {
      //   "itemName": "核酸记录",
      //   "urlPath": "nucleicAcidRecord",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/nucleicAcid-record",
      //   "pathName": "nucleicAcidRecord",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 14,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '核酸记录',
      //   "enModuleName": "module_epidemic_nucleate",
      //   "moduleCode": 'C114',
      // },
      // {
      //   "itemName": "防疫登记",
      //   "urlPath": "epidemicRegister",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/epidemic-register",
      //   "pathName": "epidemicRegister",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 15,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '防疫登记',
      //   "enModuleName": "module_epidemic_register",
      //   "moduleCode": 'C115',
      // },
      // {
      //   "itemName": "手机卡信息",
      //   "urlPath": "phoneCard",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/phone-card",
      //   "pathName": "phoneCard",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 16,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '手机卡信息',
      //   "enModuleName": "module_phone_sim",
      //   "moduleCode": 'C116',
      // },
      // {
      //   "itemName": "不动产",
      //   "urlPath": "immovable",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/immovable",
      //   "pathName": "immovable",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 17,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '不动产',
      //   "enModuleName": "module_assets_house",
      //   "moduleCode": 'C117',
      // },
      // {
      //   "itemName": "运营商业务",
      //   "urlPath": "phoneOperator",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/phoneOperator",
      //   "pathName": "phoneOperator",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-wangbashuju\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 18,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '运营商业务',
      //   "enModuleName": "module_phone_operator",
      //   "moduleCode": 'C118',
      // },
      // {
      //   "itemName": "常住人口",
      //   "urlPath": "livePerson",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/data-center/live-person",
      //   "pathName": "livePerson",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-5-query.png\",\"icon-h\":\"icon-5-query-active.png\",\"belong\":\"\"}",
      //   "sortNum": 19,
      //   "hidden": false,
      //   "parentName": "数据中心",
      //   "moduleName": '常住人口',
      //   "enModuleName": "module_population_permanent",
      //   "moduleCode": 'C119',
      // }
    ]
  },
  {
    "itemName": "全息档案",
    "status": 'enable',
    "urlPath": "/personSocial",
    "perms": "person:list,customPerson:list,person:info",
    "type": 0,
    "component": "Layout",
    "sortNum": 4,
    "hidden": false,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '全息档案',
    "moduleCode": 'D001',
    "list": [
      {
        "itemName": "地图轨迹",
        "urlPath": "Trajectory/:id",
        "perms": null,
        "type": 1,
        "component": "all-archives/person-trajectory",
        "pathName": "Trajectory",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "全息档案",
        "moduleName": '全息档案',
        "moduleCode": 'D001',
      },
      {
        "itemName": "人物档案详情",
        "urlPath": "PersonFileDetail/:id",
        "perms": null,
        "type": 1,
        "component": "common/all-archives/personFileDetail",
        "pathName": "PersonFileDetail",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "全息档案",
        "moduleName": '全息档案',
        "moduleCode": 'D001',
      },
      {
        "itemName": "档案详情",
        "urlPath": "FileDetail/:id",
        "perms": null,
        "type": 1,
        "component": "common/FileDetail",
        "pathName": "FileDetail",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "全息档案",
        "moduleName": '全息档案',
        "moduleCode": 'D001',
      },
      {
        "itemName": "人物档案",
        "urlPath": "personSocial",
        "perms": null,
        "type": 1,
        "component": "common/all-archives/person-social",
        "pathName": "personSocial",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-putongrendangan\",\"icon-h\":\"icon-4-person-active.png\",\"belong\":\"\"}",
        "sortNum": 1,
        "hidden": false,
        "parentName": "全息档案",
        "moduleName": '人物档案',
        "enModuleName": "module_normal_person_archives",
        "moduleCode": 'D102',
        "list": [
          {
            "itemName": "查询/筛选列表",
            "status": 'enable',
            "urlPath": "",
            "perms": "normal_human:list",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
            "sortNum": 1,
            "hidden": true,
            "parentName": "人物档案",
            "moduleName": '查询/筛选列表',
            "moduleCode": 'D209'
          },
          {
            "itemName": "个人详情",
            "status": 'enable',
            "urlPath": "",
            "perms": "normal_human:human_detail",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
            "sortNum": 1,
            "hidden": true,
            "parentName": "人物档案",
            "moduleName": '个人详情',
            "moduleCode": 'D211',
            "list": [
              {
                "itemName": "人物数据",
                "status": 'enable',
                "urlPath": "",
                "perms": "normal_human:human_data",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
                "sortNum": 0,
                "hidden": true,
                "parentName": "个人详情",
                "moduleName": '人物数据',
                "moduleCode": 'D302',
              },
              {
                "itemName": "图谱",
                "status": 'enable',
                "urlPath": "",
                "perms": "normal_human:atlas",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
                "sortNum": 1,
                "hidden": true,
                "parentName": "个人详情",
                "moduleName": '图谱',
                "moduleCode": 'D306',
              },
              {
                "itemName": "轨迹",
                "status": 'enable',
                "urlPath": "",
                "perms": "normal_human:human_trajectory",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
                "sortNum": 2,
                "hidden": true,
                "parentName": "个人详情",
                "moduleName": '轨迹',
                "moduleCode": 'D307',
              },
              {
                "itemName": "人物信息",
                "status": 'enable',
                "urlPath": "",
                "perms": "normal_human:human_info",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
                "sortNum": 3,
                "hidden": true,
                "parentName": "个人详情",
                "moduleName": '人物信息',
                "moduleCode": 'D308',
              }
            ]
          }
        ]
      },
      // {
      //   "itemName": "重点人档案",
      //   "createBy": "admin@admin.com",
      //   "updateBy": "admin@admin.com",
      //   "status": 'enable',
      //   "urlPath": "/",
      //   "perms": '',
      //   "type": 1,
      //   "component": "common/all-archives/person-important",
      //   "pathName": "keyPersonnelBase",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-zhongdianrendangan-01\",\"icon-h\":\"icon-0-person-active.png\",\"belong\":\"\"}",
      //   "sortNum": 2,
      //   "hidden": false,
      //   "parentName": "全息档案",
      //   "moduleName": '重点人档案',
      //   "enModuleName": "module_suspect_person_archives",
      //   "moduleCode": 'D101',
      //   "list": [
      //     {
      //       "itemName": "查询/筛选列表",
      //       "status": 'enable',
      //       "urlPath": "",
      //       "perms": "important_human:list",
      //       "type": 2,
      //       "component": "",
      //       "pathName": "",
      //       "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //       "sortNum": 1,
      //       "hidden": true,
      //       "parentName": "重点人档案",
      //       "moduleName": '查询/筛选列表',
      //       "moduleCode": 'D201'
      //     },
      //     {
      //       "itemName": "轨迹查询",
      //       "status": 'enable',
      //       "urlPath": "",
      //       "perms": "important_human:trajectory",
      //       "type": 2,
      //       "component": "",
      //       "pathName": "",
      //       "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //       "sortNum": 1,
      //       "hidden": true,
      //       "parentName": "重点人档案",
      //       "moduleName": '轨迹查询',
      //       "moduleCode": 'D202'
      //     },
      //     {
      //       "itemName": "个人详情",
      //       "status": 'enable',
      //       "urlPath": "",
      //       "perms": "important_human:human_detail",
      //       "type": 2,
      //       "component": "",
      //       "pathName": "",
      //       "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //       "sortNum": 1,
      //       "hidden": true,
      //       "parentName": "重点人档案",
      //       "moduleName": '个人详情',
      //       "moduleCode": 'D203',
      //       "list": [
      //         {
      //           "itemName": "人物信息",
      //           "status": 'enable',
      //           "urlPath": "",
      //           "perms": "important_human:human_info_profiles",
      //           "type": 2,
      //           "component": "",
      //           "pathName": "",
      //           "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //           "sortNum": 1,
      //           "hidden": true,
      //           "parentName": "个人详情",
      //           "moduleName": '人物信息',
      //           "moduleCode": 'D301',
      //           "list": [
      //             {
      //               "itemName": "基本信息",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:base_info",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "人物信息",
      //               "moduleName": '基本信息',
      //               "moduleCode": 'D402'
      //             },
      //             {
      //               "itemName": "重点人信息",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:human_info",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "人物信息",
      //               "moduleName": '重点人信息',
      //               "moduleCode": 'D415'
      //             },
      //             {
      //               "itemName": "禁毒信息",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:drug_control",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "人物信息",
      //               "moduleName": '禁毒信息',
      //               "moduleCode": 'D401'
      //             },
      //             {
      //               "itemName": "拘留信息",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:human_detention_info",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "人物信息",
      //               "moduleName": '拘留信息',
      //               "moduleCode": 'D403'
      //             },
      //           ]
      //         },
      //         {
      //           "itemName": "图谱",
      //           "status": 'enable',
      //           "urlPath": "",
      //           "perms": "important_human:human_charts",
      //           "type": 2,
      //           "component": "",
      //           "pathName": "",
      //           "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //           "sortNum": 1,
      //           "hidden": true,
      //           "parentName": "个人详情",
      //           "moduleName": '图谱',
      //           "moduleCode": 'D308',
      //           "list": [
      //             {
      //               "itemName": "关系图谱",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:relationship_atlas",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "图谱",
      //               "moduleName": '关系图谱',
      //               "moduleCode": 'D439'
      //             },
      //             {
      //               "itemName": "思维导图",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:mind_map",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "图谱",
      //               "moduleName": '思维导图',
      //               "moduleCode": 'D440'
      //             },
      //           ]
      //         },
      //         {
      //           "itemName": "关联信息",
      //           "status": 'enable',
      //           "urlPath": "",
      //           "perms": "important_human:human_relation",
      //           "type": 2,
      //           "component": "",
      //           "pathName": "",
      //           "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //           "sortNum": 1,
      //           "hidden": true,
      //           "parentName": "个人详情",
      //           "moduleName": '关联信息',
      //           "moduleCode": 'D305',
      //           "list": [
      //             {
      //               "itemName": "真实身份",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:human_relation_real",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "关联信息",
      //               "moduleName": '真实身份',
      //               "moduleCode": 'D404'
      //             },
      //             {
      //               "itemName": "虚拟账号",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:human_virtual_account",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "关联信息",
      //               "moduleName": '虚拟账号',
      //               "moduleCode": 'D405'
      //             },
      //             {
      //               "itemName": "人物图集",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "important_human:human_pics",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "关联信息",
      //               "moduleName": '人物图集',
      //               "moduleCode": 'D406'
      //             },
      //           ]
      //         }
      //       ]
      //     }
      //   ]
      // },
      // {
      //   "itemName": "自定义档案",
      //   "urlPath": "personCustom",
      //   "perms": "customPerson:add,customPerson:delete,customPerson:list,customPerson:info,customPerson:update",
      //   "type": 1,
      //   "component": "common/all-archives/person-custom",
      //   "pathName": "personCustom",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-zidingyidangan1\",\"icon-h\":\"icon-3-person-active.png\",\"belong\":\"\"}",
      //   "sortNum": 3,
      //   "hidden": false,
      //   "parentName": "全息档案",
      //   "moduleName": '自定义档案',
      //   "enModuleName": "module_custom_person_archives",
      //   "moduleCode": 'D103',
      //   "list": [
      //     {
      //       "itemName": "查询/筛选列表",
      //       "status": 'enable',
      //       "urlPath": "",
      //       "perms": "custom_human:list",
      //       "type": 2,
      //       "component": "",
      //       "pathName": "",
      //       "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //       "sortNum": 1,
      //       "hidden": true,
      //       "parentName": "自定义档案",
      //       "moduleName": '查询/筛选列表',
      //       "moduleCode": 'D212'
      //     },
      //     {
      //       "itemName": "轨迹查询",
      //       "status": 'enable',
      //       "urlPath": "",
      //       "perms": "custom_human:trajectory",
      //       "type": 2,
      //       "component": "",
      //       "pathName": "",
      //       "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //       "sortNum": 1,
      //       "hidden": true,
      //       "parentName": "自定义档案",
      //       "moduleName": '轨迹查询',
      //       "moduleCode": 'D213'
      //     },
      //     {
      //       "itemName": "新增/编辑/删除人员",
      //       "status": 'enable',
      //       "urlPath": "",
      //       "perms": "custom_human:add_edit_del_human",
      //       "type": 2,
      //       "component": "",
      //       "pathName": "",
      //       "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //       "sortNum": 1,
      //       "hidden": true,
      //       "parentName": "自定义档案",
      //       "moduleName": '新增/编辑/删除人员',
      //       "moduleCode": 'D214'
      //     },
      //     {
      //       "itemName": "个人详情",
      //       "status": 'enable',
      //       "urlPath": "",
      //       "perms": "custom_human:human_detail",
      //       "type": 2,
      //       "component": "",
      //       "pathName": "",
      //       "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //       "sortNum": 1,
      //       "hidden": true,
      //       "parentName": "自定义档案",
      //       "moduleName": '个人详情',
      //       "moduleCode": 'D215',
      //       "list": [
      //         {
      //           "itemName": "人物信息",
      //           "status": 'enable',
      //           "urlPath": "",
      //           "perms": "custom_human:human_info",
      //           "type": 2,
      //           "component": "",
      //           "pathName": "",
      //           "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //           "sortNum": 1,
      //           "hidden": true,
      //           "parentName": "个人详情",
      //           "moduleName": '人物信息',
      //           "moduleCode": 'D303',
      //           "list": [
      //             {
      //               "itemName": "基本信息",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "custom_human:base_info",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "人物信息",
      //               "moduleName": '基本信息',
      //               "moduleCode": 'D409'
      //             },
      //             // {
      //             //   "itemName": "更多信息",
      //             //   "status": 'enable',
      //             //   "urlPath": "",
      //             //   "perms": "custom_human:more_info",
      //             //   "type": 2,
      //             //   "component": "",
      //             //   "pathName": "",
      //             //   "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //             //   "sortNum": 1,
      //             //   "hidden": true,
      //             //   "parentName": "人物信息",
      //             //   "moduleName": '更多信息',
      //             //   "moduleCode": 'D410'
      //             // },
      //             // {
      //             //   "itemName": "其他证件",
      //             //   "status": 'enable',
      //             //   "urlPath": "",
      //             //   "perms": "custom_human:other_card",
      //             //   "type": 2,
      //             //   "component": "",
      //             //   "pathName": "",
      //             //   "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //             //   "sortNum": 1,
      //             //   "hidden": true,
      //             //   "parentName": "人物信息",
      //             //   "moduleName": '其他证件',
      //             //   "moduleCode": 'D430'
      //             // },
      //             // {
      //             //   "itemName": "不动产信息",
      //             //   "status": 'enable',
      //             //   "urlPath": "",
      //             //   "perms": "custom_human:real_estate_info",
      //             //   "type": 2,
      //             //   "component": "",
      //             //   "pathName": "",
      //             //   "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //             //   "sortNum": 1,
      //             //   "hidden": true,
      //             //   "parentName": "人物信息",
      //             //   "moduleName": '不动产信息',
      //             //   "moduleCode": 'D431'
      //             // },
      //             // {
      //             //   "itemName": "车辆档案",
      //             //   "status": 'enable',
      //             //   "urlPath": "",
      //             //   "perms": "custom_human:car_archives",
      //             //   "type": 2,
      //             //   "component": "",
      //             //   "pathName": "",
      //             //   "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //             //   "sortNum": 1,
      //             //   "hidden": true,
      //             //   "parentName": "人物信息",
      //             //   "moduleName": '车辆档案',
      //             //   "moduleCode": 'D432'
      //             // },
      //             // {
      //             //   "itemName": "虚拟账号",
      //             //   "status": 'enable',
      //             //   "urlPath": "",
      //             //   "perms": "custom_human:virtual_account",
      //             //   "type": 2,
      //             //   "component": "",
      //             //   "pathName": "",
      //             //   "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //             //   "sortNum": 1,
      //             //   "hidden": true,
      //             //   "parentName": "人物信息",
      //             //   "moduleName": '虚拟账号',
      //             //   "moduleCode": 'D433'
      //             // },
      //           ]
      //         },
      //         {
      //           "itemName": "关联信息",
      //           "status": 'enable',
      //           "urlPath": "",
      //           "perms": "custom_human:human_relation",
      //           "type": 2,
      //           "component": "",
      //           "pathName": "",
      //           "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //           "sortNum": 1,
      //           "hidden": true,
      //           "parentName": "个人详情",
      //           "moduleName": '关联信息',
      //           "moduleCode": 'D311',
      //           "list": [
      //             {
      //               "itemName": "真实身份",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "custom_human:human_relation_real",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "关联信息",
      //               "moduleName": '真实身份',
      //               "moduleCode": 'D441'
      //             },
      //             {
      //               "itemName": "虚拟账号",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "custom_human:human_virtual_account",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "关联信息",
      //               "moduleName": '虚拟账号',
      //               "moduleCode": 'D442'
      //             },
      //             {
      //               "itemName": "人物图集",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "custom_human:human_pics",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "关联信息",
      //               "moduleName": '人物图集',
      //               "moduleCode": 'D443'
      //             },
      //           ]
      //         },
      //         // {
      //         //   "itemName": "编辑人员",
      //         //   "status": 'enable',
      //         //   "urlPath": "",
      //         //   "perms": "custom_human:human_charts",
      //         //   "type": 2,
      //         //   "component": "",
      //         //   "pathName": "",
      //         //   "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //         //   "sortNum": 1,
      //         //   "hidden": true,
      //         //   "parentName": "个人详情",
      //         //   "moduleName": '编辑人员',
      //         //   "moduleCode": 'D309'
      //         // },
      //         {
      //           "itemName": "图谱",
      //           "status": 'enable',
      //           "urlPath": "",
      //           "perms": "custom_human:atlas",
      //           "type": 2,
      //           "component": "",
      //           "pathName": "",
      //           "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //           "sortNum": 1,
      //           "hidden": true,
      //           "parentName": "个人详情",
      //           "moduleName": '图谱',
      //           "moduleCode": 'D307',
      //           "list": [
      //             {
      //               "itemName": "关系图谱",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "custom_human:relationship_atlas",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "图谱",
      //               "moduleName": '关系图谱',
      //               "moduleCode": 'D416'
      //             },
      //             {
      //               "itemName": "思维导图",
      //               "status": 'enable',
      //               "urlPath": "",
      //               "perms": "custom_human:mind_map",
      //               "type": 2,
      //               "component": "",
      //               "pathName": "",
      //               "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //               "sortNum": 1,
      //               "hidden": true,
      //               "parentName": "图谱",
      //               "moduleName": '思维导图',
      //               "moduleCode": 'D417'
      //             },
      //           ]
      //         }
      //       ]
      //     }
      //   ]
      // },
      // {
      //   "itemName": "自定义档案_详情",
      //   "urlPath": "personCustomDetail/:id",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/all-archives/person-custom/person-detail-custom",
      //   "pathName": "personCustomDetail",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"自定义档案\"}",
      //   "sortNum": 30,
      //   "hidden": true,
      //   "parentName": "全息档案",
      //   "moduleName": '自定义档案',
      //   "enModuleName": "module_normal_person_archives",
      //   "moduleCode": 'D103',
      // },
      // {
      //   "itemName": "关系图_新建/编辑/详情",
      //   "urlPath": "Relation/:id",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/all-archives/person-custom/relation-atlas/index",
      //   "pathName": "Relation",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\"}",
      //   "sortNum": 30,
      //   "hidden": true,
      //   "parentName": "全息档案",
      //   "moduleName": '自定义档案',
      //   "moduleCode": 'D103',
      // },
      {
        "itemName": "车辆档案",
        "urlPath": "carFile",
        "perms": null,
        "type": 1,
        "component": "common/all-archives/car-archives",
        "pathName": "carFile",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-cheliangdangan\",\"icon-h\":\"icon-4-carFile-active.png\",\"belong\":\"\"}",
        "sortNum": 4,
        "hidden": false,
        "parentName": "全息档案",
        "moduleName": '车辆档案',
        "enModuleName": "module_car_archives",
        "moduleCode": 'D104',
        "list": [
          {
            "itemName": "查询/筛选列表",
            "urlPath": "carAtlas",
            "perms": 'car_archive:list',
            "type": 2,
            "component": "",
            "pathName": "carAtlas",
            "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
            "sortNum": 30,
            "hidden": true,
            "parentName": "车辆档案",
            "moduleName": '查询/筛选列表',
            "moduleCode": 'D204',
          },
          {
            "itemName": "轨迹查阅",
            "urlPath": "carAtlas",
            "perms": 'car_archive:car_trajectory',
            "type": 2,
            "component": "",
            "pathName": "carAtlas",
            "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
            "sortNum": 30,
            "hidden": true,
            "parentName": "车辆档案",
            "moduleName": '轨迹查阅',
            "moduleCode": 'D205',
          },
          {
            "itemName": "详情查阅",
            "urlPath": "carAtlas",
            "perms": 'car_archive:car_detail',
            "type": 2,
            "component": "",
            "pathName": "carAtlas",
            "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
            "sortNum": 30,
            "hidden": true,
            "parentName": "车辆档案",
            "moduleName": '详情查阅',
            "moduleCode": 'D206',
          },
          {
            "itemName": "图集查阅",
            "urlPath": "carAtlas",
            "perms": 'car_archive:car_pics',
            "type": 2,
            "component": "",
            "pathName": "carAtlas",
            "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
            "sortNum": 30,
            "hidden": true,
            "parentName": "全息档案",
            "moduleName": '图集查阅',
            "moduleCode": 'D207',
          }
        ]
      },
      {
        "itemName": "车辆档案_图集",
        "urlPath": "carAtlas",
        "perms": null,
        "type": 1,
        "component": "common/all-archives/car-archives/car-atlas",
        "pathName": "carAtlas",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "全息档案",
        "moduleName": '车辆档案',
        "moduleCode": 'D104',
      },
      {
        "itemName": "车辆档案_车辆轨迹",
        "urlPath": "carTrail",
        "perms": null,
        "type": 1,
        "component": "all-archives/car-trajectory",
        "pathName": "carTrail",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "全息档案",
        "moduleName": '车辆档案',
        "moduleCode": 'D104',
      }
    ]
  },
  // {
  //   "itemName": "分析研判",
  //   "status": 'enable',
  //   "urlPath": "/deduction",
  //   "perms": null,
  //   "type": 0,
  //   "normalImg": null,
  //   "component": "Layout",
  //   "pathName": null,
  //   "meta": null,
  //   "sortNum": 6,
  //   "hidden": false,
  //   "open": null,
  //   "parentId": 0,
  //   "moduleParentId": 0,
  //   "moduleName": '分析研判',
  //   "moduleCode": 'E001',
  //   "list": [
  //     {
  //       "itemName": "关系推演",
  //       "urlPath": "deduction",
  //       "perms": null,
  //       "type": 1,
  //       "component": "common/analysis/relationship-deduction",
  //       "pathName": "deduction",
  //       "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-guanxituiyan\",\"icon-h\":\"icon-dedution-active.png\",\"belong\":\"\"}",
  //       "sortNum": 1,
  //       "hidden": false,
  //       "parentName": "分析研判",
  //       "moduleName": '关系推演',
  //       "moduleCode": 'E101',
  //     },
  //     {
  //       "itemName": "作息分析",
  //       "status": 'enable',
  //       "urlPath": "WorkAndRest",
  //       "perms": "ana:workAndRest",
  //       "type": 1,
  //       "component": "analysis/work-and-rest-analysis",
  //       "pathName": "WorkAndRest",
  //       "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-zuoxifenxi\",\"icon-h\":\"icon-zuoxi-active.png\",\"belong\":\"\"}",
  //       "sortNum": 2,
  //       "hidden": false,
  //       "parentName": "分析研判",
  //       "moduleName": '作息分析',
  //       "moduleCode": 'E102',
  //     },
  //     {
  //       "itemName": "时空特征碰撞",
  //       "status": 'enable',
  //       "urlPath": "spaceTimeCollision",
  //       "perms": "case:list",
  //       "type": 1,
  //       "component": "analysis/space-time-collision",
  //       "pathName": "spaceTimeCollision",
  //       "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-shikongtezhengpengzhuang\",\"icon-h\":\"icon-pengzhuang-active.png\",\"belong\":\"\"}",
  //       "sortNum": 5,
  //       "hidden": false,
  //       "parentName": "分析研判",
  //       "moduleName": '时空特征碰撞',
  //       "moduleCode": 'E105',
  //     },
  //     {
  //       "itemName": "同行分析",
  //       "status": 'enable',
  //       "urlPath": "peerAnalysis",
  //       "perms": "peerRelevance,queryTimeTrack",
  //       "type": 1,
  //       "component": "analysis/walking-togethe-analysis",
  //       "pathName": "peerAnalysis",
  //       "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-tonghangfenxi\",\"icon-h\":\"icon-tongxing-active.png\",\"belong\":\"\"}",
  //       "sortNum": 4,
  //       "hidden": false,
  //       "parentName": "分析研判",
  //       "moduleName": '同行分析',
  //       "moduleCode": 'E104',
  //     },
  //     {
  //       "itemName": "时空轨迹",
  //       "status": 'enable',
  //       "urlPath": "SpaceRound",
  //       "perms": "queryTimeTrack",
  //       "type": 1,
  //       "component": "analysis/space-time-trajectory",
  //       "pathName": "SpaceRound",
  //       "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-shikongguiji\",\"icon-h\":\"icon-guiji-active.png\",\"belong\":\"\"}",
  //       "sortNum": 3,
  //       "hidden": false,
  //       "parentName": "分析研判",
  //       "moduleName": '时空轨迹',
  //       "moduleCode": 'E103',
  //     }
  //   ]
  // },
  {
    "itemName": "防控预警",
    "status": 'enable',
    "urlPath": "/controlWarn",
    "perms": null,
    "type": 0,
    "normalImg": null,
    "component": "Layout",
    "pathName": null,
    "meta": null,
    "sortNum": 5,
    "hidden": false,
    "open": null,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '防控预警',
    "moduleCode": 'H001',
    "list": [
      {
        "itemName": "防控预警",
        "urlPath": "controlWarn",
        "perms": 'control:control',
        "type": 1,
        "component": "common/control-warn/index",
        "pathName": "controlWarn",
        "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"icon-quanwensousuo\",\"icon-h\":\"\",\"belong\":\"\"}",
        "sortNum": 0,
        "hidden": false,
        "parentName": "防控预警",
        "moduleName": '防控预警',
        "moduleCode": 'H101',
      },
    ]
  },
  {
    "itemName": "应用中心",
    "status": 'enable',
    "urlPath": "/analysis",
    "perms": null,
    "type": 0,
    "normalImg": null,
    "component": "Layout",
    "pathName": null,
    "meta": null,
    "sortNum": 6,
    "hidden": false,
    "open": null,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '应用中心',
    "moduleCode": 'I001',
    "list": [
      {
        "itemName": "应用中心",
        "urlPath": "analysis",
        "perms": 'analysis',
        "type": 1,
        "component": "common/analysis-judgment/index",
        "pathName": "analysis",
        "meta": "{\"common\":true,\"hidden\":true,\"icon\":\"icon-guanxituiyan\",\"icon-h\":\"icon-dedution-active.png\",\"belong\":\"\"}",
        "sortNum": 1,
        "hidden": false,
        "parentName": "应用中心",
        "moduleName": '应用中心',
        "moduleCode": 'I101',
      },
      {
        "itemName": "应用中心详情",
        "urlPath": "analysisResult",
        "perms": 'analysisResult',
        "type": 1,
        "component": "common/analysis-judgment/components/app-result/index",
        "pathName": "analysisResult",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\",\"layout\":\"app-result\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "应用中心",
        "moduleName": '应用中心',
        "moduleCode": 'I101',
      },
      {
        "itemName": "应用中心编辑",
        "urlPath": "analysisEdit",
        "perms": 'analysisEdit',
        "type": 1,
        "component": "common/analysis-judgment/components/app-edit/index",
        "pathName": "analysisEdit",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"\",\"layout\":\"blank\"}",
        "sortNum": 31,
        "hidden": true,
        "parentName": "应用中心",
        "moduleName": '应用中心',
        "moduleCode": 'I101',
      },
    ]
  },
  /*{
    "itemName": "防控预警",
    "status": 'enable',
    "urlPath": "/MapWarn",
    "perms": null,
    "type": 0,
    "normalImg": null,
    "component": "Layout",
    "pathName": null,
    "meta": null,
    "sortNum": 6,
    "hidden": false,
    "open": null,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '防控预警',
    "moduleCode": 'F001',
    "list": [
      {
        "itemName": "防控预警",
        "urlPath": "MapWarn",
        "perms": "warn:track:add,warn:track:delete,warn:track:update,warn:track:info,warn:track:list,warn:feat:add,warn:feat:delete,warn:feat:update,warn:feat:info,warn:feat:list",
        "type": 1,
        "component": "warn/MapWarn",
        "pathName": "MapWarn",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-dituyujing\",\"icon-h\":\"router-icon-0-warn-active.png\",\"belong\":\"\"}",
        "sortNum": 1,
        "hidden": false,
        "parentName": "防控预警",
        "moduleName": '防控预警',
        "moduleCode": 'F101',
        "list": [
          {
            "itemName": "预警历史",
            "urlPath": "carAtlas",
            "perms": 'map_warn:warning_history',
            "type": 1,
            "component": "common/clueQuery/carFile/carAtlas",
            "pathName": "carAtlas",
            "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
            "sortNum": 30,
            "hidden": true,
            "parentName": "防控预警",
            "moduleName": '预警历史',
            "moduleCode": 'F201',
            "list": [
              {
                "itemName": "聚集预警",
                "urlPath": "",
                "perms": 'warning_history:crowd _warning_rules',
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
                "sortNum": 30,
                "hidden": true,
                "parentName": "预警历史",
                "moduleName": '聚集预警',
                "moduleCode": 'F311'
              },
              {
                "itemName": "特征预警",
                "urlPath": "",
                "perms": 'warning_history:feature_warning_rules',
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
                "sortNum": 30,
                "hidden": true,
                "parentName": "预警历史",
                "moduleName": '特征预警',
                "moduleCode": 'F320'
              }
            ]
          },
          {
            "itemName": "查询",
            "urlPath": "",
            "perms": 'map_warn:search',
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
            "sortNum": 30,
            "hidden": true,
            "parentName": "防控预警",
            "moduleName": '查询',
            "moduleCode": 'F211',
          },
          {
            "itemName": "规则列表",
            "urlPath": "carAtlas",
            "perms": 'map_warn:rule_list',
            "type": 1,
            "component": "common/clueQuery/carFile/carAtlas",
            "pathName": "carAtlas",
            "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
            "sortNum": 30,
            "hidden": true,
            "parentName": "防控预警",
            "moduleName": '规则列表',
            "moduleCode": 'F202',
            "list": [
              {
                "itemName": "聚集预警",
                "urlPath": "",
                "perms": 'rule_list:crowd _warning_rules',
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
                "sortNum": 30,
                "hidden": true,
                "parentName": "规则列表",
                "moduleName": '聚集预警',
                "moduleCode": 'F301',
                "list": [
                  {
                    "itemName": "新增/编辑/删除",
                    "urlPath": "",
                    "perms": 'crowd_warning_rules:add_edit_del',
                    "type": 2,
                    "component": "",
                    "pathName": "",
                    "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
                    "sortNum": 30,
                    "hidden": true,
                    "parentName": "聚集预警",
                    "moduleName": '新增/编辑/删除',
                    "moduleCode": 'F401',
                  }
                ]
              },
              {
                "itemName": "特征预警",
                "urlPath": "",
                "perms": 'rule_list:feature_warning_rules',
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
                "sortNum": 30,
                "hidden": true,
                "parentName": "规则列表",
                "moduleName": '特征预警',
                "moduleCode": 'F302',
                "list": [
                  {
                    "itemName": "新增/编辑/删除",
                    "urlPath": "",
                    "perms": 'feature_warning_rules:add_edit_del',
                    "type": 2,
                    "component": "",
                    "pathName": "",
                    "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"车辆档案\"}",
                    "sortNum": 30,
                    "hidden": true,
                    "parentName": "特征预警",
                    "moduleName": '新增/编辑/删除',
                    "moduleCode": 'F402',
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "itemName": "防控预警_预警历史",
        "urlPath": "History",
        "perms": "warn:track:add,warn:track:delete,warn:track:update,warn:track:info,warn:track:list,warn:feat:add,warn:feat:delete,warn:feat:update,warn:feat:info,warn:feat:list",
        "type": 1,
        "component": "common/warn/MapWarn/History",
        "pathName": "History",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"防控预警\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '防控预警',
        "moduleCode": 'F101',
      },
      {
        "itemName": "防控预警_预警规则",
        "urlPath": "Rules",
        "perms": "warn:track:add,warn:track:delete,warn:track:update,warn:track:info,warn:track:list,warn:feat:add,warn:feat:delete,warn:feat:update,warn:feat:info,warn:feat:list",
        "type": 1,
        "component": "common/warn/MapWarn/Rules",
        "pathName": "Rules",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"防控预警\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '防控预警',
        "moduleCode": 'F101',
      },
      {
        "itemName": "防控预警_规则_聚集预警_新建/编辑",
        "urlPath": "TrackRuleForm/:id",
        "perms": null,
        "type": 1,
        "component": "warn/MapWarn/Track/TrackRuleForm",
        "pathName": "TrackRuleForm",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"防控预警\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '防控预警',
        "moduleCode": 'F101',
      },
      {

        "itemName": "防控预警_规则_特征预警_新建/编辑",
        "urlPath": "FeatureRuleForm/:id",
        "perms": null,
        "type": 1,
        "component": "warn/MapWarn/Feature/FeatureRuleForm",
        "pathName": "FeatureRuleForm",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"防控预警\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '防控预警',
        "moduleCode": 'F101',
      },
      // {
      //   "itemName": "异常通讯",
      //   "urlPath": "MobileWarn",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/warn/MobileWarn",
      //   "pathName": "MobileWarn",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"router-icon-1-warn.png\",\"icon-h\":\"router-icon-1-warn-active.png\",\"belong\":\"\"}",
      //   "sortNum": 2,
      //   "hidden": false,
      //   "parentName": "防控预警"
      // },
      // {
      //   "itemName": "异常通讯_规则列表",
      //   "urlPath": "MobileWarnRules",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/warn/MobileWarn/Rules",
      //   "pathName": "MobileWarnRules",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"异常通讯\"}",
      //   "sortNum": 30,
      //   "hidden": true,
      //   "parentName": "防控预警"
      // },
      {
        "itemName": "区域防控",
        "urlPath": "AreaWarn",
        "perms": null,
        "type": 1,
        "component": "warn/AreaWarn/index",
        "pathName": "AreaWarn",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-quyufangkong\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
        "sortNum": 3,
        "hidden": false,
        "parentName": "防控预警",
        "moduleName": '区域防控',
        "moduleCode": 'F103',
        "list": [
          {
            "itemName": "预警历史",
            "urlPath": "",
            "perms": "area_warn:warning_history",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "区域防控",
            "moduleName": '预警历史',
            "moduleCode": 'F203',
            "list": [
              {
                "itemName": "导出",
                "urlPath": "",
                "perms": "area_warn:export",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
                "sortNum": 3,
                "hidden": false,
                "parentName": "预警历史",
                "moduleName": '导出',
                "moduleCode": 'F308',
              }
            ]
          },
          {
            "itemName": "查询/筛选",
            "urlPath": "",
            "perms": "area_warn:search",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "区域防控",
            "moduleName": '查询/筛选',
            "moduleCode": 'F212',
          },
          {
            "itemName": "新建区域",
            "urlPath": "",
            "perms": "area_warn:build_new_area",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "区域防控",
            "moduleName": '新建区域',
            "moduleCode": 'F204',
            // "list":[
            //   {
            //     "itemName": "新增/查询",
            //     "urlPath": "",
            //     "perms": "area_warn:add_edit_del",
            //     "type": 2,
            //     "component": "",
            //     "pathName": "",
            //     "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            //     "sortNum": 3,
            //     "hidden": false,
            //     "parentName": "新建区域",
            //     "moduleName": '新增/查询',
            //     "moduleCode": 'F303',
            //   }
            // ]
          }
        ]
      },
      {
        "itemName": "区域防控_新建/编辑",
        "urlPath": "AreaWarnForm/:id ",
        "perms": null,
        "type": 1,
        "component": "warn/AreaWarn/NewArea/index",
        "pathName": "AreaWarnForm",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"区域防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '区域防控',
        "moduleCode": 'F103',
      },
      {
        "itemName": "区域防控_预警规则",
        "urlPath": "AreaWarnRules",
        "perms": null,
        "type": 1,
        "component": "common/warn/AreaWarn/Rules/index",
        "pathName": "AreaWarnRules",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"区域防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '区域防控',
        "moduleCode": 'F103',
      },
      {
        "itemName": "重点防控",
        "urlPath": "ImportantWarn",
        "perms": null,
        "type": 1,
        "component": "warn/ImportantWarn/index",
        "pathName": "ImportantWarn",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-zhongdianfangkong\",\"icon-h\":\"router-icon-4-warn-active.png\",\"belong\":\"\"}",
        "sortNum": 4,
        "hidden": false,
        "parentName": "防控预警",
        "moduleName": '重点防控',
        "moduleCode": 'F104',
        "list": [
          {
            "itemName": "查询",
            "urlPath": "",
            "perms": "important_warn:search",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "重点防控",
            "moduleName": '查询',
            "moduleCode": 'F214',
          },
          {
            "itemName": "预警历史",
            "urlPath": "",
            "perms": "important_warn:warning_history",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "重点防控",
            "moduleName": '预警历史',
            "moduleCode": 'F205',
            "list": [
              {
                "itemName": "导出",
                "urlPath": "",
                "perms": "important_warn:export",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
                "sortNum": 3,
                "hidden": false,
                "parentName": "预警历史",
                "moduleName": '导出',
                "moduleCode": 'F315',
              }
            ]
          },
          {
            "itemName": "规则列表",
            "urlPath": "",
            "perms": "important_warn:rule_list",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "重点防控",
            "moduleName": '规则列表',
            "moduleCode": 'F206',
            "list": [
              {
                "itemName": "新增/编辑/删除",
                "urlPath": "",
                "perms": "important_warn:add_edit_del",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
                "sortNum": 3,
                "hidden": false,
                "parentName": "规则列表",
                "moduleName": '新增/编辑/删除',
                "moduleCode": 'F304',
              }
            ]
          }
        ]
      },
      {
        "itemName": "重点防控_规则列表",
        "urlPath": "ImportantWarnRules",
        "perms": null,
        "type": 1,
        "component": "common/warn/ImportantWarn/ImportantWarnRules/index",
        "pathName": "ImportantWarnRules",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"重点防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '重点防控',
        "moduleCode": 'F104',
      },
      {
        "itemName": "重点防控_新建/编辑",
        "urlPath": "ImportantRuleForm/:id ",
        "perms": null,
        "type": 1,
        "component": "warn/ImportantWarn/NewImportant/index",
        "pathName": "ImportantRuleForm",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"重点防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '重点防控',
        "moduleCode": 'F104',
      },
      {
        "itemName": "重点防控_历史预警",
        "urlPath": "ImportantWarnHistory",
        "perms": null,
        "type": 1,
        "component": "common/warn/ImportantWarn/ImportantWarnHistory/index",
        "pathName": "ImportantWarnHistory",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"重点防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '重点防控',
        "moduleCode": 'F104',
      },
      {
        "itemName": "边界防控",
        "urlPath": "BorderWarn",
        "perms": null,
        "type": 1,
        "component": "warn/BorderWarn/index",
        "pathName": "BorderWarn",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-bianjieyufang\",\"icon-h\":\"router-icon-3-warn-active.png\",\"belong\":\"\"}",
        "sortNum": 5,
        "hidden": false,
        "parentName": "防控预警",
        "moduleName": '边界防控',
        "moduleCode": 'F105',
        "list": [
          {
            "itemName": "查询",
            "urlPath": "",
            "perms": "border_warn:search",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "边界防控",
            "moduleName": '查询',
            "moduleCode": 'F215',
          },
          {
            "itemName": "预警历史",
            "urlPath": "",
            "perms": "border_warn:warning_history",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "边界防控",
            "moduleName": '预警历史',
            "moduleCode": 'F207',
            "list": [
              {
                "itemName": "导出",
                "urlPath": "",
                "perms": "border_warn:export",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
                "sortNum": 3,
                "hidden": false,
                "parentName": "预警历史",
                "moduleName": '导出',
                "moduleCode": 'F317',
              }
            ]
          },
          {
            "itemName": "新建边界",
            "urlPath": "",
            "perms": "border_warn:build_new_border",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "边界防控",
            "moduleName": '新建边界',
            "moduleCode": 'F210',
            // "list":[
            //   {
            //     "itemName": "查询/新增",
            //     "urlPath": "",
            //     "perms": "border_warn:add_edit_del",
            //     "type": 2,
            //     "component": "",
            //     "pathName": "",
            //     "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            //     "sortNum": 3,
            //     "hidden": false,
            //     "parentName": "新建边界",
            //     "moduleName": '查询/新增',
            //     "moduleCode": 'F305',
            //   }
            // ]
          }
        ]
      },
      {
        "itemName": "边界防控_历史预警",
        "urlPath": "BorderWarnHistory",
        "perms": null,
        "type": 1,
        "component": "common/warn/BorderWarn/BorderWarnHistory/index",
        "pathName": "BorderWarnHistory",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"边界防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '边界防控',
        "moduleCode": 'F105',
      },
      {
        "itemName": "边界防控_新建/编辑",
        "urlPath": "BorderWarnForm/:id ",
        "perms": null,
        "type": 1,
        "component": "warn/BorderWarn/NewBorder/index",
        "pathName": "BorderWarnForm",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"边界防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '边界防控',
        "moduleCode": 'F105',
      },
      {
        "itemName": "人脸防控",
        "urlPath": "FaceWarn",
        "perms": "",
        "type": 1,
        "component": "warn/FaceWarn",
        "pathName": "FaceWarn",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"icon-icon_renlianfangkong\",\"icon-h\":\"router-icon-6-warn-active.png\",\"belong\":\"\"}",
        "sortNum": 6,
        "hidden": false,
        "parentName": "防控预警",
        "moduleName": '人脸防控',
        "moduleCode": 'F106',
        "list": [
          {
            "itemName": "查询",
            "urlPath": "",
            "perms": "face_warn:search",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "人脸防控",
            "moduleName": '查询',
            "moduleCode": 'F216',
          },
          {
            "itemName": "预警历史",
            "urlPath": "",
            "perms": "face_warn:warning_history",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "人脸防控",
            "moduleName": '预警历史',
            "moduleCode": 'F208',
            "list": [
              {
                "itemName": "导出",
                "urlPath": "",
                "perms": "face_warn:export",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
                "sortNum": 3,
                "hidden": false,
                "parentName": "预警历史",
                "moduleName": '导出',
                "moduleCode": 'F318',
              }
            ]
          },
          {
            "itemName": "防控列表",
            "urlPath": "",
            "perms": "face_warn:rule_list",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "人脸防控",
            "moduleName": '防控列表',
            "moduleCode": 'F209',
            "list": [
              {
                "itemName": "新增/编辑/删除",
                "urlPath": "",
                "perms": "face_warn:add_edit_del",
                "type": 2,
                "component": "",
                "pathName": "",
                "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
                "sortNum": 3,
                "hidden": false,
                "parentName": "防控列表",
                "moduleName": '新增/编辑/删除',
                "moduleCode": 'F306',
              }
            ]
          }
        ]
      },
      {
        "itemName": "人脸防控_预警列表",
        "urlPath": "FaceWarnList",
        "perms": null,
        "type": 1,
        "component": "common/warn/FaceWarn/FaceWarnList/index",
        "pathName": "FaceWarnList",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"人脸防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '人脸防控',
        "moduleCode": 'F106',
      },
      {
        "itemName": "人脸防控_预警详情",
        "urlPath": "WarnDetail/:id ",
        "perms": null,
        "type": 1,
        "component": "common/warn/FaceWarn/WarnDetail/index",
        "pathName": "WarnDetail",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"人脸防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '人脸防控',
        "moduleCode": 'F106',
      },
      {
        "itemName": "人脸防控_新建/编辑",
        "urlPath": "newFaceWarn/:id ",
        "perms": null,
        "type": 1,
        "component": "warn/FaceWarn/newFaceWarn/index",
        "pathName": "newFaceWarn",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"人脸防控\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '人脸防控',
        "moduleCode": 'F106',
      },
      {
        "itemName": "涉黄预警",
        "urlPath": "PornographicWarn",
        "perms": "",
        "type": 1,
        "component": "common/warn/PornographicWarn",
        "pathName": "PornographicWarn",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-shehuangyujing\",\"icon-h\":\"router-icon-7-warn-active.png\",\"belong\":\"\"}",
        "sortNum": 7,
        "hidden": false,
        "parentName": "防控预警",
        "moduleName": '涉黄预警',
        "moduleCode": 'F107',
        "list": [
          {
            "itemName": "导出",
            "urlPath": "",
            "perms": "pornographic_warn:export",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "涉黄预警",
            "moduleName": '导出',
            "moduleCode": 'F218',
          }
        ]
      },
      {
        "itemName": "同行关系_展示",
        "urlPath": "PeerRelation/:id ",
        "perms": null,
        "type": 1,
        "component": "warn/PornographicWarn/PeerRelation/index",
        "pathName": "PeerRelation",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"涉黄预警\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '涉黄预警',
        "moduleCode": 'F107',
      },
      {
        "itemName": "涉黄预警_高频轨迹",
        "urlPath": "HFTrack/:id ",
        "perms": null,
        "type": 1,
        "component": "warn/PornographicWarn/HFTrack/index",
        "pathName": "HFTrack",
        "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"\",\"icon-h\":\"\",\"belong\":\"涉黄预警\"}",
        "sortNum": 30,
        "hidden": true,
        "parentName": "防控预警",
        "moduleName": '涉黄预警',
        "moduleCode": 'F107',
      },
    ],
  },*/
  {
    "itemName": "系统设置",
    "status": 'enable',
    "urlPath": "/departmentManagement",
    "perms": null,
    "type": 0,
    "normalImg": null,
    "component": "Layout",
    "pathName": null,
    "meta": null,
    "sortNum": 30,
    "hidden": true,
    "open": null,
    "parentId": 0,
    "moduleParentId": 0,
    "moduleName": '系统设置',
    "moduleCode": 'G001',
    "list": [
      {
        "itemName": "部门管理",
        "status": 'enable',
        "urlPath": "departmentManagement",
        "perms": "",
        "type": 1,
        "component": "common/system-setting/department-management",
        "pathName": "departmentManagement",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-bumenguanli\",\"icon-h\":\"icon-0-sys-active.png\",\"belong\":\"\"}",
        "sortNum": -2,
        "hidden": false,
        "parentName": "系统设置",
        "moduleName": '部门管理',
        "moduleCode": 'G101',
        "list": [
          {
            "itemName": "角色启用/禁用",
            "urlPath": "",
            "perms": "department_management:role_use_or_stop",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "部门管理",
            "moduleName": '角色启用/禁用',
            "moduleCode": 'G208',
          },
          {
            "itemName": "角色新建/编辑/删除/查看",
            "urlPath": "",
            "perms": "department_management:role_edit",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "部门管理",
            "moduleName": '角色新建/编辑/删除/查看',
            "moduleCode": 'G201',
          },
          {
            "itemName": "部门新增/重命名/删除",
            "urlPath": "",
            "perms": "department_management:add_edit_del",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "部门管理",
            "moduleName": '部门新增/重命名/删除',
            "moduleCode": 'G202',
          }
        ]
      },
      {
        "itemName": "用户管理",
        "status": 'enable',
        "urlPath": "userManagement",
        "perms": "",
        "type": 1,
        "component": "common/system-setting/user-management",
        "pathName": "userManagement",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-yonghuguanli\",\"icon-h\":\"icon-1-sys-active.png\",\"belong\":\"\"}",
        "sortNum": -1,
        "hidden": false,
        "parentName": "系统设置",
        "moduleName": '用户管理',
        "moduleCode": 'G102',
        "list": [
          {
            "itemName": "启用/禁用",
            "urlPath": "",
            "perms": "user_management:user_use_or_stop",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "用户管理",
            "moduleName": '启用/禁用',
            "moduleCode": 'G203',
          },
          {
            "itemName": "转部门",
            "urlPath": "",
            "perms": "user_management:user_transform_department",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "用户管理",
            "moduleName": '转部门',
            "moduleCode": 'G207',
          },
          {
            "itemName": "新增/编辑/删除",
            "urlPath": "",
            "perms": "user_management:add_edit_del",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "用户管理",
            "moduleName": '新增/编辑/删除',
            "moduleCode": 'G204',
          }
        ]
      },
      {
        "itemName": "密码重置申请",
        "status": 'enable',
        "urlPath": "applicationManagement",
        "perms": "",
        "type": 1,
        "component": "common/system-setting/apply-manage",
        "pathName": "applicationManagement",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-shenqingguanli\",\"icon-h\":\"icon-6-sys-active.png\",\"belong\":\"\"}",
        "sortNum": 0,
        "hidden": false,
        "parentName": "系统设置",
        "moduleName": '密码重置申请',
        "moduleCode": 'G103',
      },
      {
        "itemName": "数据管理",
        "status": 'enable',
        "urlPath": "recordsManage",
        "perms": "",
        "type": 1,
        "component": "common/system-setting/records-manage",
        "pathName": "recordsManage",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-a-zu4886\",\"icon-h\":\"icon-9-sys-active.png\",\"belong\":\"\"}",
        "sortNum": 1,
        "hidden": false,
        "parentName": "系统设置",
        "moduleName": '数据管理',
        "moduleCode": 'G110',
      },
      // {
      //   "itemName": "数据导入",
      //   "status": 'enable',
      //   "urlPath": "recordsImport",
      //   "perms": "",
      //   "type": 1,
      //   "component": "common/system-setting/records-import",
      //   "pathName": "recordsImport",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-shujudaoru\",\"icon-h\":\"icon-9-sys-active.png\",\"belong\":\"\"}",
      //   "sortNum": 1,
      //   "hidden": false,
      //   "parentName": "系统设置",
      //   "moduleName": '数据导入',
      //   "moduleCode": 'G110',
      // },
      // {
      //   "itemName": "系统监控",
      //   "status": 'enable',
      //   "urlPath": "systemMonitor",
      //   "perms": "",
      //   "type": 1,
      //   "component": "common/system-setting/system-monitor",
      //   "pathName": "systemMonitor",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-danganguanli\",\"icon-h\":\"icon-6-sys-active.png\",\"belong\":\"\"}",
      //   "sortNum": 3,
      //   "hidden": false,
      //   "parentName": "系统设置",
      //   "moduleName": '系统监控',
      //   "moduleCode": 'G111',
      // },
      {
        "itemName": "档案管理",
        "status": 'enable',
        "urlPath": "fileManage",
        "perms": "",
        "type": 1,
        "component": "common/system-setting/file-manage",
        "pathName": "fileManage",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-danganguanli\",\"icon-h\":\"icon-6-sys-active.png\",\"belong\":\"\"}",
        "sortNum": 2,
        "hidden": false,
        "parentName": "系统设置",
        "moduleName": '档案管理',
        "moduleCode": 'G109',
      },
      // {
      //   "itemName": "角色管理",
      //   "status": 'enable',
      //   "urlPath": "systemsetting",
      //   "perms": "role:info,role:list,role:add,role:update,role:delete",
      //   "type": 1,
      //   "component": "common/system-setting/role-manage",
      //   "pathName": "systemsetting",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-0-sys.png\",\"icon-h\":\"icon-0-sys-active.png\",\"belong\":\"\"}",
      //   "sortNum": 1,
      //   "hidden": false,
      //   "parentName": "系统设置",
      //   "moduleName": '角色管理',
      //   "moduleCode": 'G104',
      // },
      // {
      //   "itemName": "用户管理",
      //   "status": 'enable',
      //   "urlPath": "userManage",
      //   "perms": "user:info,user:list,user:add,user:update,user:delete,role:list",
      //   "type": 1,
      //   "component": "common/system-setting/user-manage",
      //   "pathName": "userManage",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-1-sys.png\",\"icon-h\":\"icon-1-sys-active.png\",\"belong\":\"\"}",
      //   "sortNum": 2,
      //   "hidden": false,
      //   "parentName": "系统设置",
      //   "moduleName": '用户管理',
      //   "moduleCode": 'G105',
      // },


      {
        "itemName": "日志记录",
        "status": 'enable',
        "urlPath": "logManage",
        "perms": "auth:log:list,auth:log:info",
        "type": 1,
        "component": "common/system-setting/log-manage",
        "pathName": "logManage",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-rizhijilu\",\"icon-h\":\"icon-2-sys-active.png\",\"belong\":\"\"}",
        "sortNum": 4,
        "hidden": false,
        "parentName": "系统设置",
        "moduleName": '日志记录',
        "moduleCode": 'G107'
      },
      {
        "itemName": "个人信息",
        "status": 'enable',
        "urlPath": "useInfo",
        "perms": "user:info",
        "type": 1,
        "component": "common/system-setting/use-info",
        "pathName": "useInfo",
        "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-gerenxinxi\",\"icon-h\":\"icon-3-sys-active.png\",\"belong\":\"\"}",
        "sortNum": 5,
        "hidden": false,
        "parentName": "系统设置",
        "moduleName": '个人信息',
        "moduleCode": 'G106',
        "list": [
          {
            "itemName": "修改账号",
            "urlPath": "",
            "perms": "useInfo:edit_account",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "个人信息",
            "moduleName": '修改账号',
            "moduleCode": 'G209',
          },
          {
            "itemName": "修改密码",
            "urlPath": "",
            "perms": "useInfo:edit_password",
            "type": 2,
            "component": "",
            "pathName": "",
            "meta": "{\"common\":false,\"hidden\":false,\"icon\":\"router-icon-2-warn.png\",\"icon-h\":\"router-icon-2-warn-active.png\"}",
            "sortNum": 3,
            "hidden": false,
            "parentName": "个人信息",
            "moduleName": '修改密码',
            "moduleCode": 'G210',
          }
        ]
      },
      // {
      // "id": 5,
      //   "itemName": "导入数据",
      //   "urlPath": "exportData",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/systemSetting/exportData",
      //   "pathName": "exportData",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-daorushuju\",\"icon-h\":\"icon-4-sys-active.png\",\"belong\":\"\"}",
      //   "sortNum": 5,
      //   "hidden": false,
      //   "parentName": "系统设置"
      // },
      // {
      //   "itemName": "关于平台",
      //   "status": 'enable',
      //   "urlPath": "about",
      //   "perms": null,
      //   "type": 1,
      //   "component": "common/system-setting/about",
      //   "pathName": "about",
      //   "meta": "{\"common\":true,\"hidden\":false,\"icon\":\"icon-guanyupingtai\",\"icon-h\":\"icon-5-sys-active.png\",\"belong\":\"\"}",
      //   "sortNum": 6,
      //   "hidden": false,
      //   "parentName": "系统设置",
      //   "moduleName": '关于平台',
      //   "moduleCode": 'G108',
      // }
    ]
  }
]


// 上传方式
// (function (global, factory) {
//   typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
//   typeof define === 'function' && define.amd ? define(factory) :
//   (global = typeof globalThis !== 'undefined' ? globalThis : global || self, global.allRouterBundle = factory());
// }(this, (function () { 'use strict';

//   var allRouter =[];

//   return allRouter;

// })));

