export default {
  dataType1: {
    'probe_mac_type':'探针数据',
    'probe_wifi_type': 'WIFI热点',
    'net_web_type': '审计数据',
    'probe_phone_type': '电围数据',
    'community_car_type': '停车记录',
    'community_face_type': '人脸抓拍',
    'community_gate_type': '视频门禁',
    'police_netbar_type': '网吧数据',
    'police_antiepidemic_type': '防疫数据',
    'police_hotel_type': '旅业数据',
    'bank_card_type': '银行业务',
    'epidemic_resumework_type': '复工复产',
    'epidemic_nucleate_type': '核酸记录',
    'epidemic_register_type': '防疫登记',
    'phone_sim_type': '手机卡信息',
    'assets_house_type': '不动产',
    'phone_operator_type': '运营商业务',
    'population_permanent_type': '常住人口'
  },
  dataType2: {
    '探针数据':'probe_mac_type',
    'WIFI热点': 'probe_wifi_type',
    '审计数据':'net_web_type',
    '电围数据':'probe_phone_type',
    '停车记录':'community_car_type',
    '人脸抓拍':'community_face_type',
    '视频门禁':'community_gate_type',
    '网吧数据':'police_netbar_type',
    '防疫数据':'police_antiepidemic_type',
    '旅业数据':'police_hotel_type',
    '银行业务': 'bank_card_type',
    '复工复产':'epidemic_resumework_type',
    '核酸记录': 'epidemic_nucleate_type',
    '防疫登记': 'epidemic_register_type',
    '手机卡信息': 'phone_sim_type',
    '不动产': 'assets_house_type',
    '运营商业务': 'phone_operator_type',
    '常住人口': 'population_permanent_type'
  }
}
